analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - example/**
    - example_command_results/**
    - counter_example/**
  errors:
    deprecated_member_use_from_same_package: ignore
    
linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

#    avoid_print: false
#    unnecessary_await_in_return: false
    type_annotate_public_apis: true
#    avoid_function_literals_in_foreach_calls: false
